  
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yo-client.serviceAccountName" . }}
  labels:
{{ include "yo-client.labels" . | nindent 4 }}
{{- end -}}