#!/bin/bash

PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
docker build -t $IMAGE_NAME --build-arg MICROSCANNER_TOKEN=$MICROSCANNER_TOKEN .
if [ $DOCKER_TAG == "latest" ]
then
    docker tag $IMAGE_NAME $DOCKER_REPO:$PACKAGE_VERSION
    docker push $DOCKER_REPO:$PACKAGE_VERSION
fi