version: '3.8'

services:
  yo-api:
    # build:
    #   context: .
    #   dockerfile: src/Dockerfile
    image: ghcr.io/jonfairbanks/yo-url:main
    ports:
      - "3000:3000"
    env_file:
      - .env.development
