name: Enforce PR From Develop Branch

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        if: github.head_ref != 'develop' || github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "Pull requests to main must come from develop branch."
          exit 1
