name: Enforce PR From Develop Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        if: github.base_ref != 'develop'
        run: |
          echo "Pull requests to main must come from develop branch."
          exit 1